/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmraa_Aio */

#ifndef _Included_jmraa_Aio
#define _Included_jmraa_Aio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmraa_Aio
 * Method:    loadAioNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jmraa_Aio_loadAioNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     jmraa_Aio
 * Method:    read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jmraa_Aio_read
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
