/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmraa_Gpio */

#ifndef _Included_jmraa_Gpio
#define _Included_jmraa_Gpio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmraa_Gpio
 * Method:    loadGpioNative
 * Signature: (IZZ)V
 */
JNIEXPORT void JNICALL Java_jmraa_Gpio_loadGpioNative
  (JNIEnv *, jobject, jint, jboolean, jboolean);

/*
 * Class:     jmraa_Gpio
 * Method:    dir
 * Signature: (Ljmraa/Utils/Dir;)I
 */
JNIEXPORT jint JNICALL Java_jmraa_Gpio_dir
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmraa_Gpio
 * Method:    write
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jmraa_Gpio_write
  (JNIEnv *, jobject, jint);

/*
 * Class:     jmraa_Gpio
 * Method:    read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jmraa_Gpio_read
  (JNIEnv *, jobject);

/*
 * Class:     jmraa_Gpio
 * Method:    getPin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jmraa_Gpio_getPin
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
