/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmraa_Encoder */

#ifndef _Included_jmraa_Encoder
#define _Included_jmraa_Encoder
#ifdef __cplusplus
extern "C" {
#endif
#undef jmraa_Encoder_MIN_PRIORITY
#define jmraa_Encoder_MIN_PRIORITY 1L
#undef jmraa_Encoder_NORM_PRIORITY
#define jmraa_Encoder_NORM_PRIORITY 5L
#undef jmraa_Encoder_MAX_PRIORITY
#define jmraa_Encoder_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
