/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmraa_Utils_I2cMode */

#ifndef _Included_jmraa_Utils_I2cMode
#define _Included_jmraa_Utils_I2cMode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
