/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmraa_Spi */

#ifndef _Included_jmraa_Spi
#define _Included_jmraa_Spi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmraa_Spi
 * Method:    loadSpiNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jmraa_Spi_loadSpiNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     jmraa_Spi
 * Method:    write
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_jmraa_Spi_write__B
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     jmraa_Spi
 * Method:    write
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jmraa_Spi_write___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     jmraa_Spi
 * Method:    bitPerWord
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jmraa_Spi_bitPerWord
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
