/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jlibmraa_Utils_Dir */

#ifndef _Included_jlibmraa_Utils_Dir
#define _Included_jlibmraa_Utils_Dir
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
