/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jlibmraa_Utils_Edge */

#ifndef _Included_jlibmraa_Utils_Edge
#define _Included_jlibmraa_Utils_Edge
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
