/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmraa_Encoder */

#ifndef _Included_jmraa_Encoder
#define _Included_jmraa_Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmraa_Encoder
 * Method:    loadEncoderNative
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jmraa_Encoder_loadEncoderNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jmraa_Encoder
 * Method:    getCountNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jmraa_Encoder_getCountNative
  (JNIEnv *, jobject);

/*
 * Class:     jmraa_Encoder
 * Method:    getDerivative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jmraa_Encoder_getDerivative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
