/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmraa_Utils */

#ifndef _Included_jmraa_Utils
#define _Included_jmraa_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmraa_Utils
 * Method:    usleep
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jmraa_Utils_usleep
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
